const NAMESPACE = 'clothing/auth:';

export default {
    SIGNIN_INIT: `${NAMESPACE}SIGNIN_INIT`,
    SIGNIN: `${NAMESPACE}SIGNIN`,
    SIGN_IN_SUCCESS: `${NAMESPACE}SIGN_IN_SUCCESS`,
    SIGN_IN_FAILURE: `${NAMESPACE}SIGN_IN_FAILURE`,
}